name: 📦 Build Test Tag and Publish Release

on:
  pull_request:


permissions:
  contents: write
  packages: write

jobs:
  _:
    if: github.event.pull_request.merged == true

    uses: ./.github/workflows/_build_test.yml


  publish-dockerhub:

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: docker/login-action@v3
        with:
          # implicitly docker hub
          username: wmdetravisbot
          password: ${{ secrets.WBS_PUBLISH_TOKEN }}

      - name: Push release to dockerhub
        run: |
          set -x

          docker image ls

          images=(
            "wikibase"
            "wikibase-bundle"
            "elasticsearch"
            "wdqs"
            "wdqs-frontend"
            "wdqs-proxy"
            "quickstatements"
          )

          echo "::debug::start listing images:"
          for image in "${images[@]}"; do
            echo "::debug::wikibase/${image}"
          done
          echo "::debug::end images list"
